imports:
  - { resource: services/forms.yml }
  - { resource: services/helpers.yml }
  - { resource: services/workers.yml }

parameters:
  app.version: 

services:
  orkestra.entity_manager:
    alias: doctrine.orm.entity_manager
  orkestra.guzzle_client:
    class: Guzzle\Http\Client
    arguments:
      - ''
      - { 'curl.options': { 'CURLOPT_CAINFO': %orkestra.ca_bundle.path%, 'CURLOPT_SSL_VERIFYPEER': true } }

  # Twig extensions
  orkestra.application.twig_extension:
    public: false
    class: Orkestra\Bundle\ApplicationBundle\Twig\OrkestraExtension
    calls:
      - [ setContainer, [ @service_container ] ]
    tags:
      - { name: twig.extension }

  # Listeners
  orkestra.application.user_preferences_listener:
    class: Orkestra\Bundle\ApplicationBundle\Listener\UserPreferencesListener
    arguments: [ @service_container ]
    tags:
       - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
  orkestra.application.json_response_listener:
    class: Orkestra\Bundle\ApplicationBundle\Listener\JsonResponseListener
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 128 }

  # Subscribers
  orkestra.application.subscriber.latitude_longitude:
    public: false
    class: Orkestra\Bundle\ApplicationBundle\Subscriber\LatitudeLongitudeSubscriber
    tags:
      - { name: doctrine.event_subscriber }

  