services:
  # Form types
  orkestra.type.enum:
    class: Orkestra\Bundle\ApplicationBundle\Form\EnumType
    tags:
      - { name: form.type, alias: enum }
  orkestra.type.year:
    class: Orkestra\Bundle\ApplicationBundle\Form\YearType
    tags:
      - { name: form.type, alias: year }
  orkestra.type.phone:
    class: Orkestra\Bundle\ApplicationBundle\Form\PhoneType
    tags:
      - { name: form.type, alias: tel }
  orkestra.type.datetime:
    class: Orkestra\Bundle\ApplicationBundle\Form\DateTimeType
    tags:
      - { name: form.type, alias: datetime }
  orkestra.type.entity_choice:
    class: Orkestra\Bundle\ApplicationBundle\Form\EntityChoiceType
    arguments: [ @doctrine ]
    tags:
      - { name: form.type, alias: entity_choice }
